# Generated by Django 4.0.4 on 2022-05-05 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollutantentry',
            name='country',
        ),
    ]
