# Generated by Django 4.0.4 on 2022-05-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0006_country_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutant',
            name='color',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
