# Generated by Django 4.0.4 on 2022-05-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapp',
            name='image',
            field=models.ImageField(default='/profile_default.png', upload_to='profile_pic'),
        ),
    ]
