# Generated by Django 4.0.4 on 2022-05-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_myapp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapp',
            name='url',
            field=models.CharField(default='/airpollution', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myapp',
            name='image',
            field=models.ImageField(default='/profile_default.png', upload_to='my_apps'),
        ),
    ]
