# Generated by Django 4.0.4 on 2022-05-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finances', '0003_remove_balance_date_balance_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
