# Generated by Django 4.0.4 on 2022-05-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finances', '0008_balance_date_income_updated_at_outcome_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='comment_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
