# Generated by Django 4.0.4 on 2022-05-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finances', '0009_balance_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='repetition_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='repetition_end',
            field=models.DateField(null=True),
        ),
    ]
